# Generated by Django 6.1.1 on 2026-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CableEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=100)),
                ("html", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("id",),
                "indexes": [
                    models.Index(fields=["topic", "id"], name="cable_topic_id_idx"),
                    models.Index(fields=["expires_at"], name="cable_expires_idx"),
                ],
            },
        ),
    ]
